CREATE TABLE IF NOT EXISTS series (
    name VARCHAR(255) PRIMARY KEY,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    info_path VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS blog_series (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    info_path VARCHAR(255) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    series VARCHAR(255),
    FOREIGN KEY (series) REFERENCES series(name)
      ON DELETE CASCADE
      ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS tag_blog (
    tag VARCHAR(255) NOT NULL,
    blog_id INT NOT NULL,
    PRIMARY KEY (blog_id, tag),
    FOREIGN KEY (blog_id) REFERENCES blog_series(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
    );
